# Generated by Django 5.1.1 on 2024-10-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubroutineActiveGlobalVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subroutine', models.CharField(blank=True, max_length=100, null=True)),
                ('variable_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'subroutine_active_global_vars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member', models.CharField(blank=True, max_length=100, null=True)),
                ('member_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dim', models.IntegerField(blank=True, null=True)),
                ('bounds', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'user_types',
                'managed': False,
            },
        ),
    ]
