# Generated by Django 5.1.1 on 2024-10-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dependency', models.CharField(blank=True, max_length=100, null=True)),
                ('object_used', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'module_dependency',
                'managed': False,
            },
        ),
    ]
