# Generated by Django 5.1.2 on 2025-02-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_delete_authgroup_delete_authgrouppermissions_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subroutineargs",
            name="unique_sub_args",
        ),
        migrations.RemoveConstraint(
            model_name="usertypeinstances",
            name="unique_instances",
        ),
        migrations.AddConstraint(
            model_name="subroutineargs",
            constraint=models.UniqueConstraint(
                fields=("subroutine", "arg_type", "arg_name", "dim"),
                name="unique_sub_args",
            ),
        ),
        migrations.AddConstraint(
            model_name="usertypeinstances",
            constraint=models.UniqueConstraint(
                fields=("module", "instance_type", "instance_name"),
                name="unique_instances",
            ),
        ),
    ]
