# Generated by Django 5.1.2 on 2024-11-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_variables"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Modules",
            fields=[
                ("module_id", models.AutoField(primary_key=True, serialize=False)),
                ("module_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "modules",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubroutineArgs",
            fields=[
                ("arg_id", models.AutoField(primary_key=True, serialize=False)),
                ("arg_type", models.CharField(max_length=100)),
                ("arg_name", models.CharField(max_length=100)),
                ("dim", models.IntegerField()),
            ],
            options={
                "db_table": "subroutine_args",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubroutineCalltree",
            fields=[
                ("parent_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "subroutine_calltree",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubroutineLocalArrays",
            fields=[
                ("local_arry_id", models.AutoField(primary_key=True, serialize=False)),
                ("array_name", models.CharField(max_length=100)),
                ("dim", models.IntegerField()),
            ],
            options={
                "db_table": "subroutine_local_arrays",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Subroutines",
            fields=[
                ("subroutine_id", models.AutoField(primary_key=True, serialize=False)),
                ("subroutine_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "subroutines",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TypeDefinitions",
            fields=[
                ("define_id", models.AutoField(primary_key=True, serialize=False)),
                ("member_type", models.CharField(max_length=100)),
                ("member_name", models.CharField(max_length=100)),
                ("dim", models.IntegerField()),
                ("bounds", models.CharField(max_length=100)),
                ("active", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "type_definitions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserTypeInstances",
            fields=[
                ("instance_id", models.AutoField(primary_key=True, serialize=False)),
                ("instance_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "user_type_instances",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Variables",
        ),
    ]
