# Generated by Django 5.1.2 on 2025-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_subroutineargs_unique_sub_args_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usertypeinstances",
            name="unique_instances",
        ),
        migrations.RenameField(
            model_name="typedefinitions",
            old_name="module",
            new_name="type_module",
        ),
        migrations.RenameField(
            model_name="usertypeinstances",
            old_name="module",
            new_name="inst_module",
        ),
        migrations.AlterUniqueTogether(
            name="typedefinitions",
            unique_together={
                ("user_type", "member_type", "member_name", "type_module")
            },
        ),
        migrations.AddConstraint(
            model_name="usertypeinstances",
            constraint=models.UniqueConstraint(
                fields=("inst_module", "instance_type", "instance_name"),
                name="unique_instances",
            ),
        ),
    ]
